# Generated by Django 3.1.7 on 2021-03-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_auto_20210228_1735'),
        ('product', '0003_auto_20210208_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='unit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('shop', 'name')},
        ),
    ]
