# Generated by Django 3.1.6 on 2021-02-08 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0002_auto_20210203_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargetype',
            options={'ordering': ['updated']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['updated']},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['updated']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['updated']},
        ),
        migrations.AlterModelOptions(
            name='shopitem',
            options={'ordering': ['updated']},
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={'ordering': ['updated']},
        ),
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='tax_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_products', to='pos.chargetype'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.shop'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_products', to='pos.shopping'),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shopitem',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_products', to='pos.tax'),
        ),
    ]
