# Generated by Django 3.1.6 on 2021-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20210209_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], max_length=20, null=True),
        ),
    ]
