# Generated by Django 3.1.6 on 2021-02-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20210213_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='shop',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='shopping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_products', to='pos.shopping'),
            preserve_default=False,
        ),
    ]
