# Generated by Django 3.1.6 on 2021-02-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20210213_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='due',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
