# Generated by Django 3.1.6 on 2021-02-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20210215_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='total',
            field=models.FloatField(),
        ),
    ]
