# Generated by Django 3.1.6 on 2021-02-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20210208_1552'),
        ('pos', '0011_auto_20210216_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Shopping',
        ),
        migrations.AddField(
            model_name='payment',
            name='shopping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.shopping'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.paymenttype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.people'),
        ),
    ]
