# Generated by Django 3.1.6 on 2021-02-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('partial', 'PARTIAL'), ('due', 'DUE')], max_length=50, null=True),
        ),
    ]
