# Generated by Django 3.1.6 on 2021-02-23 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0015_cashin_cashout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expanse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expanse_history', to='pos.shop', verbose_name='Shop')),
            ],
            options={
                'ordering': ['updated'],
                'abstract': False,
            },
        ),
    ]
