# Generated by Django 3.1.6 on 2021-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_expanse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashin',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashout',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
