# Generated by Django 3.1.6 on 2021-02-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_auto_20210223_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expanse',
            name='reason',
        ),
        migrations.AddField(
            model_name='expanse',
            name='note',
            field=models.TextField(default=7843),
            preserve_default=False,
        ),
    ]
