# Generated by Django 3.1.6 on 2021-02-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20210223_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cash_amount',
            field=models.IntegerField(default=0),
        ),
    ]
