# Generated by Django 3.1.6 on 2021-02-24 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20210218_1742'),
        ('pos', '0019_shop_cash_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoppings', to='people.people'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shoppings', to='pos.shop'),
            preserve_default=False,
        ),
    ]
