# Generated by Django 3.1.7 on 2021-02-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20210224_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
