# Generated by Django 3.1.6 on 2021-02-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210203_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['updated']},
        ),
    ]
