# Generated by Django 3.1.6 on 2021-02-03 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pin', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^(?:\\+8801|01)?(\\d{9})$'), django.core.validators.MinLengthValidator(limit_value=11)])),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Family Name')),
                ('is_staff', models.BooleanField(default=False, null=True, verbose_name='Staff status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.media_upload_path, verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Spouse')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Father')),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Mother')),
                ('nid', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{10}|\\d{13}|\\d{17})$', message='Numeric 10/13/17 digits (ex: 1234567890)')], verbose_name='National ID')),
                ('passport', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{7}$', message='Alphanumeric 9 characters (ex: PA3456789)')], verbose_name='Passport')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address')),
                ('thana', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thana')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('division', models.CharField(blank=True, max_length=255, null=True, verbose_name='Division')),
                ('postal', models.CharField(blank=True, max_length=4, null=True, verbose_name='Postal Code')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
            ],
        ),
    ]
