# Generated by Django 3.1.6 on 2021-02-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_staff_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
